version: '3'
services:
  web:
    image: nginx:1.15.6
    container_name: web-server
    ports:
      - "12121:80"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
  app:
    build: ./docker/php
    container_name: php-app
    volumes:
      - .:/var/www/html
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3333:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
    mysql-data: